### ISSUE TITLE
AngularFireDatabase doesn't execute functions when an empty list should be returned

### ISSUE THREAD

**Issue by mateusduraes** [angular/angularfire2#1220]
Hello, seems like the AngularFireDatabase is not handling empty lists in the observables.

```typescript
constructor(private afDb: AngularFireDatabase) {}
// ommited code
public userExists(email: string): Observable<boolean> {
  return this.afDb.list('/clients', ref =>
    ref.orderByChild('email').equalTo(email))
    .valueChanges()
    .map((users: User[]) => users.length > 0);
}
```

When i call the method with an email that exists in my realtime database, everything is fine, but if the observable should return an empty list, it is not triggered.

**Comment by guillefd** [comment]
Same here, also ```snapshotChanges()``` doesn´t trigger when list is empty

**Comment by jamesdaniels** [comment]
K, I fixed in AFS I'll grab AFDB tonight + cut a new RC.

**Comment by jamesdaniels** [comment]
FYI this is a little trickier with RTDB + the new arch. Still in progress.

**Comment by yaozuwang** [comment]
Thanks James

**Comment by DennisSmolek** [comment]
Heads up, getting this as well... 
[core firebase.js says a snapshot should return null if empty](https://firebase.google.com/docs/reference/js/firebase.database.Query#on) but with the latest angularFire I dont get anything until a value exists. 

`return this.af.list('/revisions/' + contentId + '/' + draftId).valueChanges();` and `snapshotChanges()` are both never firing their subscriptions..

but: 
```
const ref = firebase.database().ref('/revisions/' + contentId + '/' + draftKey);
                    ref.once('value', snapshot => {
                        console.log('Firebase once returning:', snapshot.val());
```
fires with `Firebase once returning:null`

I had the listener setup with an `init()` binding and everything was waiting for the callback....

**Comment by hvsharma63** [comment]
This issue still exists. When **where** queries are added in collection via reference & if the collection is empty, the subscription is not fired, on **.valueChanges()** 
![image](https://user-images.githubusercontent.com/19151036/193258366-475ae029-fe22-43ca-a9b4-b16afd0cc799.png)
