### ISSUE TITLE
Firestore does not work with Angular Universal and AngularFire2 on Firebase Functions

### ISSUE THREAD

**Issue by phpet** [angular/angularfire2#1745]
**Angular:**
`6.0.6`

**Firebase:**
`5.0.4`

**AngularFire:**
`5.0.0-rc.10`

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
`OS: Windows 10`
`Node version: 8.11.2`

**Steps to set up and reproduce**

Clone this repository: https://github.com/phpet/ssr

npm run build:ssr
firebase deploy

### Debug output

** Errors in the Firebase Functions logs **

```
Unhandled Promise rejection: Cannot read property 'firestore' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'firestore' of undefined
    at new AngularFirestore (/user_code/node_modules/angularfire2/bundles/firestore.umd.js:148:29)
    at _createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:8204:20)
    at _createProviderInstance$1 (/user_code/node_modules/@angular/core/bundles/core.umd.js:8166:26)
    at resolveNgModuleDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:8129:21)
    at NgModuleRef_.get (/user_code/node_modules/@angular/core/bundles/core.umd.js:8837:16)
    at resolveDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:9202:45)
    at createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:9076:85)
    at createDirectiveInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:8959:20)
    at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:10179:36)
    at createRootView (/user_code/node_modules/@angular/core/bundles/core.umd.js:10093:5) TypeError: Cannot read property 'firestore' of undefined
    at new AngularFirestore (/user_code/node_modules/angularfire2/bundles/firestore.umd.js:148:29)
    at _createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:8204:20)
    at _createProviderInstance$1 (/user_code/node_modules/@angular/core/bundles/core.umd.js:8166:26)
    at resolveNgModuleDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:8129:21)
    at NgModuleRef_.get (/user_code/node_modules/@angular/core/bundles/core.umd.js:8837:16)
    at resolveDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:9202:45)
    at createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:9076:85)
    at createDirectiveInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:8959:20)
    at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:10179:36)
    at createRootView (/user_code/node_modules/@angular/core/bundles/core.umd.js:10093:5)
```

** Screenshots **

https://imgur.com/5Ybcdw5

### Expected behavior

Injecting the AngularFirestore variable in the constructor of the AppComponent class should work without errors.

### Actual behavior

The browser shows a `504 Gateway Time-out` error and the Firebase Functions logs show the error above.

I also tried with the latest version of AngularFire2 `5.0.0-rc.11` and it doesn't work either.

### Interesting facts

I tried replacing the angularfire2 library with angularfire-lite and it worked, so it's definitely related to the combination of AngularFire2 and Firestore.

**Comment by davideast** [comment]
@phpet This unfortunately a known issue with Cloud Functions and AF2. We are working on a fix. 

It's not surprising that AngularFireLite worked as it simply just switches to REST calls on the server. This is a quick fix but it becomes more complicated with authentication. It also increases the bundle size of the application since you're shipping two network clients. A fun fact here is that AngularFireLite is actually heavier than AngularFire2.

I'll keep you updated in this thread.

**Comment by phpet** [comment]
@davideast thanks for the update.

Unfortunately, ever since you started that "[server side frender](https://www.youtube.com/watch?v=gxCu5TEmxXE)" video last September, I tried again and again and could never quite make SSR work on Firebase Functions. So, you see, somehow it's your fault. :)

Now, I was able to make it work on Node8 in App Engine but I really like the simplicity and ease of mind of Firebase Functions. So I guess my question is, should I give up and implement it with App Engine or should I wait for the fix so I can use my favorite Firebase services? And if I should wait, how much do you think this would take?

Really appreciate your time spent on this.

Let me know if there is anything I can do to help.

**Comment by maktarsis** [comment]
Is there any news?

Please solve it.

**Comment by kanafghan** [comment]
I would really love for this to be fixed :-|

Have been trying to make it work the past 2 days.

**Comment by JancoBH** [comment]
Is there any news? :(

**Comment by jamesdaniels** [comment]
While we are diagnosing troubles with the Cloud Functions enivornment, I'd
suggest spinning your code up on AppEngine.

**Comment by patrickmichalina** [comment]
Server side auth has still not been addressed for both firestore and rtdb. No repo owners have given help for this issue in this or other tickets.

**Comment by jamesdaniels** [comment]
@patrickmichalina let's keep it on topic here please.

**Comment by VRCorp** [comment]
Hi @jamesdaniels, @davideast,
 
Without adding pressure on you, do you have a rough idea about a date for the fix to be delivered? Are we speaking about days? months?

Why this question? => to know if I can include this functionality in my next project release planned for the end of this month, or if I have to postpone it.

Thank you guys !
(and thanks for your hard work !)

**Comment by jamesdaniels** [comment]
We've not found any bugs here, like many of the issues floating around, this is likely caused by a bad combination of node_modules.

**Comment by jamesdaniels** [comment]
The main problem is the firebase JS SDK is not developed with the intention of developers installing `@firebase/*` anything by themselves, as they are 0.x releases and unstable. 

Yarn complains about missing peer deps, developer installs them, breaks everything, everyone is sad and frustrated.

There are lingering & inconsistent problems with Zone.js on Cloud Functions, with their flavor of node, which have yet to be diagnosed; but I don't think you're that far. We're won't have bandwidth from the Functions team to hunt down those issues until they come out of beta. Before that we're still suggesting people deploy their SSR apps on AppEngine.

**Comment by BluebambooSRL** [comment]
Hi @jamesdaniels, @davideast 
Do you know if there is any update on this?

Many thanks for the work/information that you provide.
Federico

**Comment by danwulff** [comment]
With the announcement of the Node 8 runtime, will this now work?
https://firebase.googleblog.com/2018/08/cloud-functions-for-firebase-config-node-8-timeout-memory-region.html

**Comment by JancoBH** [comment]
I have the same question of @danwulff

**Comment by kanafghan** [comment]
@danwulff and @JancoBH FYI, I have been trying to do so the last 2 days but without any luck :disappointed:

**Comment by kanafghan** [comment]
Out of curiosity, I've tried to experiment with how to make Firebase realtime-database work with Angular Universal and Cloud Functions using the newly added Node.js 8 runtime. To do so, I have created a [demo/experiment app](https://github.com/kanafghan/ng-ssr-gcf).

The good news is that it is working, but as long as we do not access `database()` from `firebase-admin` in the startup script, i.e. during deployment of the functions. The `database()` access should happen during runtime of the function(s).

**Comment by fcalderon** [comment]
I just learned about this issue the hard way :cry: 
```
OS (environment): Docker image node:carbon (hosted on Ubuntu)
node version: v8.10.0
```
I spent a few hours trying to debug my app which has hanging for some reason. The hanging started after pushing a fix to a bug which was preventing a call to `AngularFireDatabase#object`. it was hanging because of this, right were `AngularFireDatabase#object` was being called. However, there was no error, no warning, and no log, from AngularFire indicating that it doesn't work on SSR. 

I was wondering if, while this issue is resolved, an error can be thrown from AngularFireDatabase, if called on the server side, to indicate that this is not supported instead of just hanging for ever?

**Comment by jamesdaniels** [comment]
Solved in recent releases, docs are up for review #1841

**Comment by odineshrao** [comment]
i am too facing the issue with AngularFire2 and cloud function:
ERROR TypeError: Cannot read property 'storage' of undefined
    at new AngularFireStorage

**Comment by maktarsis** [comment]
@odineshrao , my problem is solved in recent release (@angular/fire)

**Comment by odineshrao** [comment]
@maktarsis ya, my problem is also solved after update angularfire2

**Comment by calibri87** [comment]
> @phpet This unfortunately a known issue with Cloud Functions and AF2. We are working on a fix.
> 
> It's not surprising that AngularFireLite worked as it simply just switches to REST calls on the server. This is a quick fix but it becomes more complicated with authentication. It also increases the bundle size of the application since you're shipping two network clients. A fun fact here is that AngularFireLite is actually heavier than AngularFire2.
> 
> I'll keep you updated in this thread.

Did this get fixed? because im having trouble with angular universal and firestore

**Comment by wdumlao1** [comment]
I still can't get firestore to work on SSR. Been trying for days. No errors on build or serving the node express app. It just doesn't pre-render on server side. When adding a timeout will render the html after a few seconds.
