### ISSUE TITLE
Working Configuration

### ISSUE THREAD

**Issue by Kamshak** [angular/angularfire2#1776]
Hey, does anyone have this working at the moment with universal & normal hmr build?
I'm running into all kinds of issues (some have been closed but are still present) and i'm getting to the point where I have absolutely no idea how to get this to run on the 5.0 version.

If you have it working could you share your lock file and package versions? (firebase, rxjs, zone.js and  angularfire)

Not working:
- angularfire2 rc.10 and firebase 5.0.4: This works on Client but in universal throws 
```
Unhandled Promise rejection: Cannot read property 'filter' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'filter' of undefined
    at _firebaseAppFactory (/home/valentin/frantz2/dist/server.js:131228:73)
    at /home/valentin/frantz2/dist/server.js:130456:95
    at ZoneDelegate.module.exports../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (/home/valentin/frantz2/dist/server.js:276985:26)
    at WtfZoneSpec.module.exports../node_modules/zone.js/dist/wtf.js.WtfZoneSpec.onInvoke (/home/valentin/frantz2/dist/server.js:276511:92)
    at ZoneDelegate.module.exports../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (/home/valentin/frantz2/dist/server.js:276984:32)
    at Zone.module.exports../node_modules/zone.js/dist/zone-node.js.Zone.run (/home/valentin/frantz2/dist/server.js:276735:43)
    at NgZone.module.exports../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (/home/valentin/frantz2/dist/server.js:42036:28)
    at new AngularFireAuth (/home/valentin/frantz2/dist/server.js:130455:26)
    at _createClass (/home/valentin/frantz2/dist/server.js:46543:20)
    at _createProviderInstance$1 (/home/valentin/frantz2/dist/server.js:46505:26) TypeError: Cannot read property 'filter' of undefined
    at _firebaseAppFactory (/home/valentin/frantz2/dist/server.js:131228:73)
    at /home/valentin/frantz2/dist/server.js:130456:95
    at ZoneDelegate.module.exports../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (/home/valentin/frantz2/dist/server.js:276985:26)
    at WtfZoneSpec.module.exports../node_modules/zone.js/dist/wtf.js.WtfZoneSpec.onInvoke (/home/valentin/frantz2/dist/server.js:276511:92)
    at ZoneDelegate.module.exports../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (/home/valentin/frantz2/dist/server.js:276984:32)
    at Zone.module.exports../node_modules/zone.js/dist/zone-node.js.Zone.run (/home/valentin/frantz2/dist/server.js:276735:43)
    at NgZone.module.exports../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (/home/valentin/frantz2/dist/server.js:42036:28)
    at new AngularFireAuth (/home/valentin/frantz2/dist/server.js:130455:26)
    at _createClass (/home/valentin/frantz2/dist/server.js:46543:20)
    at _createProviderInstance$1 (/home/valentin/frantz2/dist/server.js:46505:26)
```
- angularfire2 rc.11 and firebase 5.2.0; doesn't work on client, didn't try universal: #1707

**Comment by Kamshak** [comment]
Has anyone gotten this to work? I can't figure it out, i've sunk at least 8 hours into this with just 0 progress...

If anyone has any idea i'd appreciate any hint!

I've tried importing everything in my main module to make sure it's there
```ts
import { initializeApp, auth as auth2 } from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
import '@firebase/auth';
import '@firebase/database';
require('firebase/database');
```
this seems to require every conceivable build of the thing (esm, cjs) but still once i initialzeApp i get the errors "TypeError: app.auth is not a function". 
```js
/* harmony import */ var angularfire2__WEBPACK_IMPORTED_MODULE_13__ = __webpack_require__(/*! angularfire2 */ "./node_modules/angularfire2/index.js");
/* harmony import */ var firebase_app__WEBPACK_IMPORTED_MODULE_14__ = __webpack_require__(/*! firebase/app */ "./node_modules/firebase/app/dist/index.cjs.js");
/* harmony import */ var firebase_app__WEBPACK_IMPORTED_MODULE_14___default = /*#__PURE__*/__webpack_require__.n(firebase_app__WEBPACK_IMPORTED_MODULE_14__);
/* harmony import */ var firebase_auth__WEBPACK_IMPORTED_MODULE_15__ = __webpack_require__(/*! firebase/auth */ "./node_modules/firebase/auth/dist/index.esm.js");
/* harmony import */ var firebase_database__WEBPACK_IMPORTED_MODULE_16__ = __webpack_require__(/*! firebase/database */ "./node_modules/firebase/database/dist/index.esm.js");
/* harmony import */ var _firebase_auth__WEBPACK_IMPORTED_MODULE_17__ = __webpack_require__(/*! @firebase/auth */ "./node_modules/@firebase/auth/dist/auth.esm.js");
/* harmony import */ var _firebase_database__WEBPACK_IMPORTED_MODULE_18__ = __webpack_require__(/*! @firebase/database */ "./node_modules/@firebase/database/dist/index.cjs.js");
/* harmony import */ var _firebase_database__WEBPACK_IMPORTED_MODULE_18___default = /*#__PURE__*/__webpack_require__.n(_firebase_database__WEBPACK_IMPORTED_MODULE_18__);
```
Yet in my "firebase_app__WEBPACK_IMPORTED_MODULE_14__" (which is the firebase namespace from firebase/app) it gives me INTERNAL.factories as an empty object.

My webpack resolve is pretty standard: ``` 
// for client
resolve: {
    mainFields: ['browser', 'module', 'main' ],
    extensions: ['.ts', '.js', '.json'],
    alias: {
      ...require('rxjs/_esm2015/path-mapping'), // https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#build-and-treeshaking
      assets: root('src/assets')
    },
    unsafeCache: true
  }
// for universal
resolve: {
    mainFields: ['module', 'main' ],
    extensions: ['.ts', '.js', '.json'],
    alias: {
      ...require('rxjs/_esm2015/path-mapping'), // https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#build-and-treeshaking
      assets: root('src/assets')
    },
    unsafeCache: true
  }
```

**Comment by jamesdaniels** [comment]
We released rc.11 to address this. https://github.com/angular/angularfire2/releases

Also don't directly require or install any of the `@firebase/*` modules.

**Comment by Kamshak** [comment]
Thanks @jamesdaniels, unfortunately using rc.11 doesn't seem to change anything, if I do everything by the guide

1) angularfire2 rc.11
2) firebase@^5.0.3 (matches angularfire package.json)
3) do not require any firebase modules at all
4) Import the modules
```
AngularFireModule.initializeApp(FIREBASE_JSON),
  AngularFireDatabaseModule,
  AngularFireAuthModule,
``` 

I still receive 
```
VM1367 main.browser.ts:36 TypeError: app.auth is not a function
    at eval (VM2053 auth.js:18)
    at ZoneDelegate.invoke (VM1531 zone.js:387)
    at Zone.run (VM1531 zone.js:137)
    at NgZone.runOutsideAngular (VM1735 core.js:3988)
    at new AngularFireAuth (VM2053 auth.js:16)
    at _createClass (VM1735 core.js:8495)
    at _createProviderInstance$1 (VM1735 core.js:8457)
    at initNgModule (VM1735 core.js:8390)
    at new NgModuleRef_ (VM1735 core.js:9116)
    at createNgModuleRef (VM1735 core.js:9105)
```

**Comment by Kamshak** [comment]
Ping @jamesdaniels, is there anything i could try or do to debug this?

**Comment by mazeethd** [comment]
**possible work around: try manually initializing firebase as below**
`
firebase.initializeApp(Config)
`

i have faced a similar issue but different environment. i was working with ionic and phone authentication. the same code which was working earlier was not working with latest update with error saying default app not initialized. 
this error is raised irrespective on initialization via angularfire2
after two days of struggle found a workaround by manually calling firebase initialization
not sure this can solve for your environment. but it had worked for me :-)

**Comment by calibri87** [comment]
I still couldn't get this working. I'm using angular universal and I get this error still: 

**TypeError: app.auth is not a function**

I import these modules into my app module:

```
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireAuthModule,
    AngularFirestoreModule,
    AngularFireStorageModule,
```

**My versions:**

```
    "@angular/fire": "^5.1.2",
    "firebase": "^5.9.3",

```

**Comment by calibri87** [comment]
> Ping @jamesdaniels, is there anything i could try or do to debug this?

Did you get anywhere with this?

**Comment by Kamshak** [comment]
> > Ping @jamesdaniels, is there anything i could try or do to debug this?
> 
> Did you get anywhere with this?

In my case It was related to the webpack config, I had the firebase module different times in the bundle.
