### ISSUE TITLE
Bug: When loading an Item form a Collection, then Loading the whole Collection, the List has only this one Item

### ISSUE THREAD

**Issue by JonasJW** [angular/angularfire2#1972]
### Version info

**Angular:**7.1.0

**Firebase:** 5.7.0

**AngularFire:**5.1.1

### How to reproduce these conditions

I have created a small project to reproduce the problem, you can find it here: https://github.com/JonasJW/ngfPossibleBug
Just open the console, click (Fetch List), (Fetch Item) and (Fetch List) again, to see the problem in the console.

I hope this repo reproduces this problem (for me it does). I spend quite a bit setting it up.

**Steps to set up and reproduce**

I'm nut sure. Probably just download repo, do `npm i` and then `ng serve`

### Expected behavior

If I load one Item and then the List, the List still should contain all Items in my collection.

### Actual behavior

loading the List of Items works fine itself. How ever, when I load one Item from that list first and then load the whole list again, I only get a list with that one previous loaded item in it.

The Methods I use are these:

    async loadFullProgramm(id: string) {
        return new Promise(resolve => {
            this.db.collection('Programms').doc(id).valueChanges().subscribe(
                async (programm: Programm) => {
                    programm.id = id;
                    await this.loadSections(programm);
                    this.selectedProgramm = programm;
                    console.log('loaded Programm Status', programm.sections);
                    resolve(programm);
                }
            );
        });
    }

    async loadExerciseForTutor(programmId: string, sectionId: string, routineIndex: string, exerciseIndex: string) {
        return new Promise<Exercise>(resolve => {
            this.db.collection('Programms').doc(programmId).collection('Sections').doc(sectionId).valueChanges().subscribe(
                async (sec: Section) => {
                    const exercise: Exercise = sec.week[routineIndex].exercises[exerciseIndex];
                    // exercise.preset = await this.loadPreset(exercise.presetKey);
                    // exercise.tutor = await this.loadTutor(exercise.tutorKey);
                    console.log('loaded Exercise', sec);
                    resolve(exercise);
                }
            );
        });
    }

    async loadSections(programm: Programm) {
        return new Promise(resolve => {
            const pipe = this.db.collection('Programms').doc(programm.id).collection('Sections').snapshotChanges().pipe(
                map(changes => changes.map(a => {
                    const section = a.payload.doc.data() as Section;
                    section.id = a.payload.doc.id;

                    return section;

                }))
            );
            const sub = pipe.subscribe(
                (sections: Section[]) => {
                    console.log(sections);
                    programm.sections = sections;
                    // Build the routines (load the presets)
                    for (const section of sections) {
                        for (const routine of section.week) {
                            if (routine) {
                                // this.loadPresetsToRoutine(routine);
                            }
                        }
                    }
                    sub.unsubscribe();
                    resolve();
                }
            );
        });
    }

**Comment by alberthoekstra** [comment]
I think you don’t use the promise the way it should. I believe promises are used to retrieve an object once and your able to await it to be sure you retrieve the object. 

Load full program does subscribe on a observable and return resolves the promise multiple time probably. I’m not sure that’s the result you are looking for. 

I think you should rewrite it to an observable expression optionally save the result in an subject variable or just add the take(1) operator so you only get the value once from Firebase.

Same thing for load exercises.

**Comment by alberthoekstra** [comment]
Check [PR](https://github.com/JonasJW/ngfPossibleBug/pull/1).
Fixed it after adding the take operator.

**Comment by JonasJW** [comment]
Thanks for the help!

I'm not 100% sure if I fully understand what you mean but I do actually want to await my programm and I don't really care at this point if there will be an update to the programm data. So awaiting a promise should be fine to my knowledge.

However I did update my minimum repo so it doesn't use any Promises and my problem still exists. I also cleaned up a lot of code thats not neccessary to show the problem. Here are the updated functions:

    async loadExerciseForTutor(programmId: string, sectionId: string, routineIndex: string, exerciseIndex: string) {
        this.db.collection('Programms').doc(programmId).collection('Sections').doc(sectionId).valueChanges().subscribe(
            async (sec: Section) => {
                console.log('loaded Section Item', sec);
            }
        );
    }

    async loadFullProgramm(id: string) {
        this.db.collection('Programms').doc(id).valueChanges().subscribe(
            async (programm: Programm) => {
                programm.id = id;
                this.loadSections(programm);
            }
        );
    }

    private async loadSections(programm: Programm) {
        const pipe = this.db.collection('Programms').doc(programm.id).collection('Sections').snapshotChanges().pipe(
            map(changes => changes.map(a => {
                const section = a.payload.doc.data() as Section;
                section.id = a.payload.doc.id;

                return section;

            }))
        );
        const sub = pipe.subscribe(
            (sections: Section[]) => {
                programm.sections = sections;
                console.log(programm.sections, 'Loaded Sections List');
                sub.unsubscribe();
            }
        );
    }

**Comment by alberthoekstra** [comment]
Awaiting an observable doesn’t mean the observable will just trigger once. Therefor use the take(1) operator. 

Check the pull request in the previous post. 

Btw. After you ‘piped’ the take operator. You can do .toPromise() to get it as a promise.

**Comment by JonasJW** [comment]
Ah Thank you! Now I get it. Using `take(1)` seems to work. I really appreciate the help!

**Comment by jamesdaniels** [comment]
Closing but feel free to continue discussing.
